// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8d7ogxbe9dxKYbxZ2i5m9L4dozMSj5Q',
    appId: '1:14150986692:web:ef8764c63995ff6b6b1291',
    messagingSenderId: '14150986692',
    projectId: 'fir-flutter-ac738',
    authDomain: 'fir-flutter-ac738.firebaseapp.com',
    storageBucket: 'fir-flutter-ac738.appspot.com',
    measurementId: 'G-2Y8EDVJWD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFttAFzY_3rU1ILubVxZSrckC8FYMYd9Q',
    appId: '1:14150986692:android:3dfeb7aaa62623f06b1291',
    messagingSenderId: '14150986692',
    projectId: 'fir-flutter-ac738',
    storageBucket: 'fir-flutter-ac738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdk7OP_7g48lzn673cv_HGFd0xFLClug',
    appId: '1:14150986692:ios:efa94e08436d57b36b1291',
    messagingSenderId: '14150986692',
    projectId: 'fir-flutter-ac738',
    storageBucket: 'fir-flutter-ac738.appspot.com',
    iosBundleId: 'com.example.pruebaGaleria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdk7OP_7g48lzn673cv_HGFd0xFLClug',
    appId: '1:14150986692:ios:efa94e08436d57b36b1291',
    messagingSenderId: '14150986692',
    projectId: 'fir-flutter-ac738',
    storageBucket: 'fir-flutter-ac738.appspot.com',
    iosBundleId: 'com.example.pruebaGaleria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM8d7ogxbe9dxKYbxZ2i5m9L4dozMSj5Q',
    appId: '1:14150986692:web:d4fb3e57410a53876b1291',
    messagingSenderId: '14150986692',
    projectId: 'fir-flutter-ac738',
    authDomain: 'fir-flutter-ac738.firebaseapp.com',
    storageBucket: 'fir-flutter-ac738.appspot.com',
    measurementId: 'G-FBPS6B4VW4',
  );
}
